apiVersion: v1
kind: Pod
metadata:
  name: my-web-pod
spec:
  containers:
    - name: my-web-container
      image: my-web-server
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-web-service
spec:
  selector:
    app: my-web-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
